### ISSUE TITLE
Anytone 868 

### ISSUE THREAD

**Issue by M6NBP** [N4IRS/MMDVM-Install#10]
Hi
Not sure if this is the correct place to post this, but will give it a try.

STM32_DVM_PiHat V3 (BLUE) Board on Pi-Star
Anytone 868 radios having issues with timing and not getting into the repeater.
This was first seen by myself on the Duplex Hotspots and was finally fixed with a new firmware update a few months back. ( Firmware HS_Hat V 1.4.8 ) Also on the Duplex board it would drop a TX at around 60sec. I have not had a chance to fully test this on this board. 

With the radio you have to key up a few times to get in.
Leaving a long pause 3 to 5 seconds always seam to help 

This issue has been talked about over the last few days in the UK on Tg2350 Ref4400 and this is why I am posting this to see if it can be fixed.

**Comment by N4IRS** [comment]
Are you compiling the firmware yourself or are you waiting for a pre-compiled binary? I will be compiling firmware for all 3 versions of the board on the first of the month. This is the schedule I'll keep unless a major issue is found.

**Comment by M6NBP** [comment]
I was just going by this link
http://www.repeater-builder.com/products/pdfs/Upgrade_STM32_DVM_PiHat_v3.pdf

The version I am on now is mmdvm 20180723

**Comment by M6NBP** [comment]
Would not know how to compile myself

**Comment by M6NBP** [comment]
I managed to get mmdvm_f4_v3.hex | 2018-10-01 05:26 | installed.
It still shows a V20180723 on Pi-Star dash 

Anyway the issue is still present with the Anytone radio

**Comment by N4IRS** [comment]
Pi-Star does not show the complete sign-on string. G4KLX does not change the date string every time there is a revision. You can use the github SHA to determine exactly what changes are in the firmware file you have uploaded.

Since the firmware is current with the MMDVM source code, I suggest you post a question on the MMDVM list. I do not have a Anytone radio to test with.

**Comment by M6NBP** [comment]
Thank you for getting back to me 
Do you have a link for MMDVM source code list and I will post on that as well 

Many thanks

**Comment by N4IRS** [comment]
https://groups.yahoo.com/neo/groups/mmdvm/info
https://github.com/g4klx/MMDVM
