### ISSUE TITLE
compilation for M17 mode fails

### ISSUE THREAD

**Issue by acfnews** [N4IRS/MMDVM-Install#14]
Hi Steve,

I am having issues compiling the firmware for the STM32_DVM (pihat v3) and new M17 mode. 

I followed your instruction as described in the steps, but there are two issues:
- with the master branch I can compile, and a hex file is compiled and can be programmed on the modem, but the MMDVMHost is not able to use it:
`E: 2021-05-16 11:53:27.781 Unable to read the firmware version after six attempts`
- with the M17_AX25_FM branch, following the same instruction, I get this error:
```
MMDVM# make -f Makefile.CMSIS
make: *** No rule to make target 'SampleRB.h', needed by 'obj/DMRDMOTX.o'.  Stop.
```

If you have a bit of time to have a look ?

Best regards,

Ron

**Comment by N4IRS** [comment]
Ron,
For the V3 board:
make clean
make dvm

Steve N4IRS

**Comment by acfnews** [comment]
Steve, thanks!  
With that it does compile! It will make some testings with that file the coming days!

**Comment by acfnews** [comment]
Hi Steve,

I have restarted my investigations. Our remote repeater was running PI-star, and we decided to get rid of that, and just compile the stuff ourselves on top of RasperryOS. Yesterday we reinstalled the OS (remote site, difficult to enter), and now I am trying to get things working again remotely.

I am succeeding in building both the MMDVMhost, and MMDVM firmware binaries, and program the STM32. So far so good.
I am using the branch 'M17_AX25_FM'

However, the firmware(s) I create, doo not seem to work for the digital modes. No response in either log file or repeater function. Analog FM does work. The digital modes do work when using an older (FM) firmware, so I do have a solid reference point.

Using the self-build firmware, the following is printed in the log, which seem quite OK:
```
I: 2021-06-15 10:30:47.180 MMDVM protocol version: 2, description: MMDVM RB_STM32_DVM(446) 20210508 12.0000 MHz GitID #43b53fe
I: 2021-06-15 10:30:47.180 CPU: ST-Micro ARM, UDID: 390020001151373436383037
I: 2021-06-15 10:30:47.180 Modes: D-Star YSF NXDN M17 FM
```

Now I have some questions, to verify I am not missing something:
1)
From this GitHub repo (MMDVM-Install/STM32) I have installed all the packages as described in 'required-libs.sh'.
Without them, compilation does fail. I expect this is still an up-to-date procedure.

2)
I did not install the stm32cube_fw_f1_v140.zip files in ./opt as described in 'get-src.sh'
Compilation does not complain about missing items, or might this be a reason why my firmware is not working?

3)
Last there are 2 files, which I guess are specific for the STM32 PIHat I guess:
SerialRB.h and Config.h

There are some new items in the original Config.h (eg. #define MODE_xxx, and #define SERIAL_SPEED)
My Config.h looks like:
 
$ cat Config.h  | egrep -v ^'(\/\/|^$)'
/*
 *   Copyright (C) 2015,2016,2017,2018,2020 by Jonathan Naylor G4KLX
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the Free Software
 *   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */
#if !defined(CONFIG_H)
#define  CONFIG_H
#define MODE_DSTAR
#define MODE_YSF
#define MODE_NXDN
#define USE_NXDN_BOXCAR
#define MODE_M17
#define MODE_FM
#define EXTERNAL_OSC 12000000
#define SERIAL_SPEED 460800 // Only works on newer board M4, M7, Teensy. External FM should work with this
#define USE_COS_AS_LOCKOUT
#define ARDUINO_MODE_PINS
#define STM32F1_POG
#define SEND_RSSI_DATA
#endif



I have attached my compiled firmware version. 

Could you have a look if my described steps are correct, and if on your side compiling the same set produces the same, or a different firmware file?

This is for the Blue board, v3 version.


Many, many thanks in advance,

Ronald




[mmdvm_f4.hex.zip](https://github.com/N4IRS/MMDVM-Install/files/6655072/mmdvm_f4.hex.zip)

**Comment by acfnews** [comment]
Steve,

I have a bit more success, I have succeeded in building the following working combinations (branches) of firmware/software:
- FM
- M17

Both have a working YSF and Analog function (I cannot test other digital modes)

However, when building M17_AX25_FM, I am loosing the Analog repeater function.

Starting the mmdvmhost shows:

```
I: 2021-06-19 19:22:58.619 MMDVM protocol version: 2, description: MMDVM RB_STM32_DVM(446) 20210617 NO TCXO GitID #f4e1c0b
I: 2021-06-19 19:22:58.620 CPU: ST-Micro ARM, UDID: 390020001151373436383037
I: 2021-06-19 19:22:58.620 Modes: D-Star DMR YSF P25 NXDN M17 FM POCSAG AX.25

```


Not sure where this goes, wrong, at least I do have some better confidence in how to build both the firmware/software.

Would you be willing to give this branch a quick test?
My resulting hex file has sha256sum :
700f0b8602fedcf109db06e41777515c51bf080d146554b3bc67ee8e164f3e65  bin/mmdvm_f4.hex



73'

Ron

**Comment by acfnews** [comment]
Steve, the Config.h file is quite different in the M17_AX25_FM branch.
Also the speed is increased : #define SERIAL_SPEED 460800

Any feedback is appreciated !

**Comment by N4IRS** [comment]
Ron,
My testing is done with the M17_AX25_FM branch of both MMDVM and MMDVMHost
For the serial speed I'm testing at 460800 since most people will want FM networking.

**Comment by acfnews** [comment]
It's working now! Just build the latest firmware and host software.
