### ISSUE TITLE
openocd and some config change required

### ISSUE THREAD

**Issue by dk5ras** [N4IRS/MMDVM-Install#4]
The make procedure requires openocd, however your package scripts do not install this. I used this for manual installation:

cd /usr/local/src
wget https://sourceforge.net/projects/openocd/files/openocd/0.10.0/openocd-0.10.0.zip
unzip openocd-0.10.0.zip
cd openocd-0.10.0
./configure
make
sudo make install

However I am not sure better put something like that in required-libs.sh or in get-src.sh. 

Also I don't know if even a "sudo apt install openocd" would be sufficient.

Additionally I was informed that in  /usr/local/share/openocd/scripts/interface/stlink-v2.cfg the vendor ID needs to be changed from 0x3748 to 0x374b. However I could imagine that this only applies to USB connection.

With these additions manually applied I finally was able to build and install the firmware on a STM32F105.

**Comment by N4IRS** [comment]
Ralph,
Thanks for the info. I usually just do a make -f Makefile.CMSIS or make -f Makefile.CMSIS program_bl which I think uses st32flash. I will update to add openocd anyway.

73, Steve N4IRS

**Comment by dk5ras** [comment]
Well, when I had a look into the Makefile.CMSIS it appeared to me that also openocd is used. My knowledge is not that good that I could determine for what reason :)

I thought this may be one of those things that people doing this regularly have on their machines anyway while a newbie stumbles over the missing prerequisite :) At least now you know there may be something to consider.

Thanks a lot, and with best regards

Ralph, dk5ras.

**Comment by N4IRS** [comment]
Ralph,
openocd is used if you do a "make -f Makefile.CMSIS program" It is not used for "make -f Makefile.CMSIS program_bl"

Thanks, Steve
