### ISSUE TITLE
modem down after flash new firmware

### ISSUE THREAD

**Issue by ct1jib** [N4IRS/MMDVM-Install#7]
Hi,

Have a STM32DV v2 (red). Today decide load the last firmware, all of this because the RSSI do not work.

I,ve follow your readme step by step without any problem. At the end do a raspberry shutdown remove power and the JP1 and reconnect the power. The STM lose the "ramping" leds on start only the Power led lights on and the software tell's something like "I quit after 6 attempts".

For some reason the STM don't boot the firmware, only DFU mode works.

Can you help?? or give another option for STM to come back to life.

Thanks

**Comment by N4IRS** [comment]
There was a change made to the firmware that causes the problem. I have updated the instructions to reflect the changes needed. 

To recover the board, you will need a ST-Link programmer
This is the programmer:
<https://www.ebay.com/itm/ST-Link-V2-Mini-STM8-STM32-STLINK-Simulator-Download-Programming-Unit-with-Cover/322478832246?hash=item4b153c7a76:g:3usAAOSwls5Y6xBM>

while you are waiting for the device, add the 6 pin male header to JP2

Find and Download "STM32 ST-Link Utility) I'm running Version 4.0.0
It's a Windows program. I run it under Windows 7 32 bit.
You will want to have the schematic for the red board handy. <http://www.repeater-builder.com/products/pdfs/STM32_DVM_v2.pdf>
The connections are 4 wires. The pinout for the ST-Link is on the side of the device.
3.3V        Pin 1 JP2
Ground   Pin 3 JP2
SWDIO    Pin 2 JP2
SWCLK    Pin 4 JP2

One note: The ST-Link will power the board. I suggest you work on the board disconnected from the Pi.
You can the use the ST-Link to upload firmware to the board.

Or, you can ship me the board, and I will do it for you.

Steve N4IRS

**Comment by ct1jib** [comment]
Thanks Steve,
I'll do that

**Comment by ct1jib** [comment]
Problem solved without JTAG!, the serialRB was the solution

Thanks Steve
