### ISSUE TITLE
STM32-DVM V2a after firmwareupdate not boot

### ISSUE THREAD

**Issue by df3dt** [N4IRS/MMDVM-Install#8]
After Firmwareupdate (no errors) the stm32-dvm board (red V2) not boot. Only blue led (power) is on.
Please Help.
73 Uwe DF3DT

**Comment by N4IRS** [comment]
Check /usr/src/MMDVM/SerialRB.h and make sure the the line reads
const uint16_t SERIAL_RINGBUFFER_SIZE = 370U;

Recompile firmware and re-flash

**Comment by df3dt** [comment]
Hello Steve, thaks for answer.
I`m change in SerialRB.h Ringbuffer_size to 340u and recompile and re.flash.
The same, blue LED is only on.

**Comment by N4IRS** [comment]
Are you unable to put the board in bootloader mode?

**Comment by df3dt** [comment]
how am I to do?

**Comment by N4IRS** [comment]
For the STM32-DVM USB
Disconnect STM32-DVM from the host
Insert JP1 jumper
Connect STM32-DVM to the host
PWR, ACT and DMR should be lit solid, NOT flashing.

For the STM32-DVM PiHat
Shutdown the Raspberry Pi
Disconnect power to Raspberry Pi
Insert JP1 jumper
Power ON the Raspberry Pi
PWR, ACT and DMR should be lit solid, NOT flashing.

Are you running Pi-Star with a Pi-Hat?

**Comment by df3dt** [comment]
Ok ok, sorry my english not so good. hi hi
Here the board is STM32-DVM USB v2a
Disconnect the board set JP1 an connect to USB
PWR, ACT and DMR lit solid, NOT flashing
After flashing disconnect from USB and JP1 off
only blue LED

**Comment by N4IRS** [comment]
This is with:
const uint16_t SERIAL_RINGBUFFER_SIZE = 370U;
in SerialRB.h ?

If that is the case, I will have to try it myself this weekend and debug.

Steve

**Comment by df3dt** [comment]
Thanks steve
const uint16_t SERIAL_RINGBUFFER_SIZE = 370U; 
is in to the SerialRB.h
I,m looking forward to your answer. Hope, you are successfull.
Best regards Uwe DF3DT

**Comment by vk3amc** [comment]
Hi Steve

I  just tried to update fw on red board v2a also and have exactly the same issue as Uwe. Blue led only after firmware update. No errors when makefile. Programmed fine. I used the extra procedure to rename mmdvmhost to mmdvmhost.save. And I did remember to put it back. Followed procedure  on MMDVM-Install/STM32-DVM/

David

**Comment by vk3amc** [comment]
Confirmed:

const uint16_t SERIAL_RINGBUFFER_SIZE = 370U;

Regards David

**Comment by df3dt** [comment]
Hello David,
here with const uint16_t SERIAL_RINGBUFFER_SIZE = 370U; in Serial.RB the same (blue led)
No led ramping after power on
Regards Uwe

**Comment by df3dt** [comment]
Sorry no closed

**Comment by vk3amc** [comment]
I think only you can reopen it Uwe.

**Comment by N4IRS** [comment]
Guys,
For now, use the firmware here. 
<http://dvswitch.org/files/HAM/MMDVM/Version_2_Firmware/> until I have 
time to troubleshoot what changes were made that broke the firmware.

73, Steve N4IRS

**Comment by vk3amc** [comment]
Thanks Steve

Do we copy that to /srv/MMDVM-Install/STM32-DVM folder. Sorry for basic questions, it's the first time I've updated firmware.

Regards David

**Comment by N4IRS** [comment]
For Pi-Hat:
Put the board in bootloader mode
stm32flash -w file_name.hex -v /dev/ttyAMA0

For USB:
Put the board in bootloader mode
stm32flash -w file_name.hex -v /dev/ttyUSB0

**Comment by df3dt** [comment]
Bingo Steve, thanks for help.
STM32 Modem now ok......  +1: 
fine weekend de DF3DT Uwe

**Comment by vk3amc** [comment]
Not so much luck here. The STM32 will only stay in boot loader mode for 60 seconds which is not long enough for pi-star to boot and get to SSH.

I'm not a linux person. Any ideas?
David

**Comment by N4IRS** [comment]
Try renaming /etc/mmdvmhost.
login
gain root access
rpi-rw
cd /etc
mv mmdvmhost mmdvmhost.save
poweroff
Put board in BL mode.

Steve

**Comment by vk3amc** [comment]
Thanks Steve

That worked. Pi Star now showing 20180327.

Regards
David

**Comment by N4IRS** [comment]
Good to hear. I'll look into what has changed with the current firmware 
and ley people know.

Steve

**Comment by ct1jib** [comment]
Hi Steve 

I do some changes, and try the last MMDVM from GIT because last changes on dapnet use and others. The thing it's not easy for a rookie and the STM32DV Hat dont boot, even with STLink and  nothing, roollback and wait for news from you.

Thanks

**Comment by bi7jta** [comment]
Today I also catch not boot issue , when compile the new code from your github, hope you can fix it soon, thanks very much!

**Comment by N4IRS** [comment]
Which board? Use the firmware from 
<http://dvswitch.org/files/HAM/MMDVM/Version_2_Firmware/>
or <http://dvswitch.org/files/HAM/MMDVM/Version_3_Firmware/>

**Comment by bi7jta** [comment]
Thank you for your quick reply ,I have try, it can boot  ,but can not decode data, I guess your compile config.h setting 12MHz, my TCXO is 19.2MHz.

**Comment by N4IRS** [comment]
Is it a STM32F105 Micro Controller?

**Comment by bi7jta** [comment]
Yes,

**Comment by N4IRS** [comment]
Revert back to this commit 
<https://github.com/g4klx/MMDVM/tree/d6c1bea80ae1fd150111bb7a692bb5320f3beed0>
Edit the config to match your board and make:
make -f Makefile.CMSIS

73, Steve N4IRS

**Comment by N4IRS** [comment]
Make sure you replace the SerialRB.h

**Comment by bi7jta** [comment]
Thank you very much, when I replace https://github.com/g4klx/MMDVM/blob/master/SerialRB.h ,the same result,  I use the SCH from https://github.com/wojciechk8/MMDVM_pog ,and work with Raspberry Pi GPIO and USB.
I will try again. I compile use your script(20180223) in this github, can boot and work well. I compare all your commit after 20180223, just find add SerialRB.h. 
Thanks for your help.

de bi7jta.

**Comment by bi7jta** [comment]
Hi N4IRS, follow your guide
"
Revert back to this commit
<https://github.com/g4klx/MMDVM/tree/d6c1bea80ae1fd150111bb7a692bb5320f3beed0>
Make sure you replace the SerialRB.h
Edit the config to match your board and make:
make -f Makefile.CMSIS
"
It work !
Thank again. 
By the way ,if I want to compile new version of MMDVM(G4KLX) code, use POCSAG feature, what should I do? Sorry for bother.

de bi7jta,73!

**Comment by N4IRS** [comment]
The latest version of MMDVM with POCSAG does not work with the STM32F105
